### ISSUE TITLE
Calculation of Elitetroops

### ISSUE THREAD

**Issue by botoxi** [ljosberinn/resources-helper--legacy#21]
Hi,

I think, the calculation of elitetroops isn't correct. It's different to the "r.jakumo.org" page.
if i calculate the price by my own, i am able to confirm the price of r.jakumo.

greetz

**Comment by ljosberinn** [comment]
r.jakumo.org is missing the base unit craft price which is the current KI market price of the troop to be created

![33207378_834348263442398_6098306815278186496_n](https://user-images.githubusercontent.com/29307652/40360364-48a943bc-5dc6-11e8-9532-5a843cc36dcd.jpg)

craft price + 60 * weapons + 30 * electronics + 1 * gold

11.988.945 + 60 * 435.510 + 30 * 62.002 + 1 * 63.010 = `40.042.615`

whilst jakumo still shows 

`29.273.075`

please close the issue if this resolves it :)
