### ISSUE TITLE
Missing "Elektrotechnik" on "drones" in "Resourcenfluss"

### ISSUE THREAD

**Issue by mhagenbruch** [ljosberinn/resources-helper--legacy#22]
Maybe im blind, but in the "Resourcenfluss" tab, there is for Eletrotechnik only the "Medizintechnik" listet. But drones needs "Elektrotechnik" too.

**Comment by ljosberinn** [comment]
Hi,

the "Ressourcenfluss" is designed to only produce products worth producing - anything that makes a loss won't be shown as effectively being produced and Trucks as well as Drones and Silicone typically create loss when produced.
